### PR TITLE
Oscar scrapper

### PR DESCRIPTION
**Pull request by yoannLafore**
This PR aims to add a scrapper to get the movies that own an oscar.

The script scrap the official `oscars.org` website to get the name of the movies that got an oscar.
In practice, it takes as argument:
- `--base_url URL` the URL to the oscars website (by default `https://www.oscars.org/ceremonies`)
- `--year_interval BEGIN_YEAR END_YEAR` to choose a period to scrap
- `--oscar_categories  [CATEGORIES ...]` the list of categories to scrape, if none are provided, the script will scrap all categories by default
- `--output_file OUTPUT_FILE` the name of the output file with scrapped dataset, by default `oscar_winners.csv`

And the output dataset contains the following columns
- `movie_name` : The name of the movie ( :warning:  This is not a key because a movie might have won multiple oscars)
- `oscar_category` : The category of the oscar
- `year` : The year the movie won/got nominated to the oscar
- `winner` : True if the movie won the oscar, False if it was only nominated

### CODE REVIEW

**Review by camillelnne — COMMENTED** [review]
Should we add retry logic or error handling in get_page_source ? in case of network issue.
Else LGTM :)

**Comment by yoannLafore** [comment]
After discussions with the team, we made the decision to also scrap the oscar nominees to get more data to work with.
Thus a new column `winner` is added with `True` meaning that the movie won the oscar and `False` meaning that the movie only got nominated.

**Comment by yoannLafore** [comment]
Thanks for the suggestion @camillelnne !
However, after looking into it, I realized that because we are using a driver and not a http request there is no easy/clean way to detect an error in the query.
Also, given the one-time run nature of the script, I believe it might be easier to simply relaunch it in case an error happens.
What do you think ?

**Comment by camillelnne** [comment]
Sounds good @yoannLafore!
For reference, could you please provide the number of oscars winners we scraped vs nominees. If that's not too hard to do, so we can justify our choice.

**Comment by yoannLafore** [comment]
Thanks !
For the period spanning 1980 to 2020 we have:
- 982 oscar winners
- 3589 oscar nominees (but not winner)

**Pull request merged**
